### ISSUE TITLE
[Bug] replicas feature broken with pooling?

### ISSUE THREAD

**Issue by sebastianhopkins-lh** [aembke/fred.rs#138] opened 2023-05-12 11:06 UTC
Redis version - 6.2.6
Platform - linux
Using Docker and/or Kubernetes - both
Deployment type - cluster with replicas

I've been using RedisPool with a Clustered ServerConfig (all else in RedisConfig defaulted) for a while. Recently we've realised that we should be preferably sending all commands (get, and mget) to replica nodes, so I tried out the replicas feature of this crate, and called `.replicas()` on the RedisPool. This worked fine in an environment without replica nodes, but in an environment with replica nodes, all commands timed out (!). The clustered config's .host has a list of all nodes in both scenarios.

**Comment by aembke** [comment] 2023-05-12 22:07
Yeah, there's a few issues with the replica implementation in 6.2.1. The latest build in `main` should fix it, and I'm planning on releasing 6.2.2 this weekend with those changes and the 2 open PRs.

**Comment by sebastianhopkins-lh** [comment] 2023-05-15 14:39
Just updated to 6.3.0, this appears to be working. Will close when I have the data to confirm it

**Comment by sebastianhopkins-lh** [comment] 2023-05-23 13:20
I ended up having to stop using the replicas client due to strangely high request latency, unfortunately I don't have the data to confirm whether it's working or not.

**Comment by aembke** [comment] 2023-10-06 22:17
I made some pretty invasive changes to the replica routing logic in 7.x that should address this (starting at https://crates.io/crates/fred/7.0.0-rc.1). I did some scale testing and couldn't reproduce this anymore, but let me know if you still see issues here.

**Comment by aembke** [comment] 2023-10-08 23:34
Closing for now, but please let me know if you still see this in [7.0.0](https://crates.io/crates/fred/7.0.0).

**Closed by aembke** 2023-10-08 23:34 UTC
Labels: bug
