### ISSUE TITLE
Creating connection hangs when connecting in clustered mode

### ISSUE THREAD

**Issue by lamalex** [aembke/fred.rs#40] opened 2022-04-13 18:01 UTC
I am trying to connect to a redis cluster, running locally via docker with:
```rs
let cfg = ServerConfig::new_clustered(vec![(settings.host, settings.port)])
let client = RedisClient::new(cfg);
let _jh = client.connect(None);
let _ = client.wait_for_connect().await;
```
but it's just hanging a `wait_for_connect`. If I change to a single node and use `ServerConfig::new_centralized(settings.host, settings.port)` I am able to connect and issue commands.

**Comment by aembke** [comment] 2022-04-14 15:13
Hi @lamalex,

I _think_ I know what the issue is here (docker + clustered redis are subtle and somewhat complicated to use together), but before we go down that road would you mind running your code with `RUST_LOG=fred=trace` and sending the trace logs over? As long as you're not using the `network-logs` feature there wont be any sensitive info in the trace logs.

Just in case it is what I suspect it is - maybe take a look at [this doc](https://github.com/aembke/fred.rs/blob/feat/resp3-support/tests/minikube.md) I wrote regarding minikube+docker, since I think most of it also applies in your case as well.

**Comment by aembke** [comment] 2022-06-01 16:54
Hey @lamalex, I'm going to close this for now but feel free to re-open it or start a discussion in the other tab if you have any issues with this setup. I've encountered this issue before in a few different languages and I'm most likely going to publish a doc on how to do it in a way that will save you some headaches down the road.

**Closed by aembke** 2022-06-01 16:54 UTC
