### ISSUE TITLE
add support for  Redis Cluster pipeline 

### ISSUE THREAD

**Issue by i18n-now** [aembke/fred.rs#233] opened 2024-04-03 08:55 UTC
when I use fcall & set , cause CROSSSLOT error

![image](https://github.com/aembke/fred.rs/assets/145643935/87ba2666-407c-4b14-b3a2-8503a5c50214)

![image](https://github.com/aembke/fred.rs/assets/145643935/6782c4a3-1022-49d6-874a-7e85bbcf822b)

https://redis-py-cluster.readthedocs.io/en/stable/pipelines.html

Just like in redis-py, redis-py-cluster queues up all the commands inside the client until execute is called. But, once execute is called, redis-py-cluster internals work slightly differently. It still packs the commands to efficiently transmit multiple commands across the network. But since different keys may be mapped to different nodes, redis-py-cluster must first map each key to the expected node. It then packs all the commands destined for each node in the cluster into its own packed sequence of commands. It uses the redis-py library to communicate with each node in the cluster.

jedis:Cluster pipelining
https://github.com/redis/jedis/pull/1455

**Comment by aembke** [comment] 2024-04-03 14:42
Hi @i18n-now,

I don't think your issue involves pipelines, but for what it's worth the client currently works how you describe. The issue isn't that `SET` and `FCALL` are going to different cluster nodes, but rather that the keys in your `fcall` args (`&cache.user[..]` and `&[ext as u8][..]`) are mapping to different hash slots.

There are cross-slot pipeline tests that run against a cluster with different key slots here: https://github.com/aembke/fred.rs/blob/main/tests/integration/other/mod.rs#L303-L316, and I suspect you can also repro your issue even if you remove the `pipeline()` call and just use `cache.kv.fcall(...)`.

I'd also note that most of these multi-key commands require that all the keys map to the same hash slot, not just the same cluster node. In my experience this effectively means you have to use hash tags in your scripting keys if you want this to work well in practice. 

You can also use the re-exported [redis_keyslot](https://docs.rs/fred/latest/fred/util/fn.redis_keyslot.html) to check this as well. 

I'd recommend changing your key structure to include some kind of stable identifier in a hash tag: https://redis.io/docs/reference/cluster-spec/#hash-tags

**Comment by aembke** [comment] 2024-04-06 17:15
Closing for now, but let me know if you have any other questions. If you're using this in the context of a session management layer I'd maybe suggest using a user ID as the hash tag.

**Closed by aembke** 2024-04-06 17:15 UTC

**Comment by i18n-now** [comment] 2024-04-07 04:58
Hello, my Lua function above only has one key, (note that &cache.user[..] and &[ext as u8][..] are concated)

**Comment by aembke** [comment] 2024-04-08 02:16
I took a closer look and it looks like the issue is in the Lua function. The scripting docs mention:

> Important: to ensure the correct execution of scripts, both in standalone and clustered deployments, all names of keys that a script accesses must be explicitly provided as input key arguments. The script should only access keys whose names are given as input arguments. Scripts should never access keys with programmatically-generated names or based on the contents of data structures stored in the database.

But in the Lua function you're calling ZRANGE on `key`, and `key` came from `ARGS`, not `KEYS`. In the `set_txt` function if you move `hash` into the first parameter you'll still likely get a CROSSSLOT error, but now you'll be able to address the issue with hash tags.

**Comment by i18n-now** [comment] 2024-04-08 05:46
the full lua script is here 
https://github.com/i18n-api/srv/blob/main/rust/redis.lua
this ZSCORE functions is 
```
local ZSCORE = function(key, member)
	local r = redis.call("ZSCORE", key, member)
	if r then
		return r.double
	end
end
```
then
```
	local zset = KEYS[1]
	local key = ARGS[1]
	local id = ZSCORE(zset, key)
```
zset is this key, key is the member


I am not using redis, but the latest version of kvrocks （ https://kvrocks.apache.org/ ）.

Is this a server side implementation issue? (I don’t think so)

Or should the pipeline be distributed to different servers on the client side?
